"""Default TOML config templates for each method.

Used by ``flow-inviscid init <method>`` to generate a starting config file.
"""

# --------------------------------------------------
# method-specific TOML templates
# --------------------------------------------------

TANGENT_CONE = """\
# Generated by: flow-inviscid init tangent-cone

[method]
name = "tangent_cone"
"""

NEWTONIAN = """\
# Generated by: flow-inviscid init newtonian

[method]
name = "newtonian"
"""

SHOCK_EXPANSION = """\
# Generated by: flow-inviscid init shock-expansion

[method]
name = "shock_expansion"
"""

# --------------------------------------------------
# registry: method name -> template string
# --------------------------------------------------
TEMPLATES: dict[str, str] = {
    "tangent_cone":    TANGENT_CONE,
    "newtonian":       NEWTONIAN,
    "shock_expansion": SHOCK_EXPANSION,
}
