"""Default TOML config templates for each method.

Used by ``flow-inviscid init <method>`` to generate a starting config file.
"""

# --------------------------------------------------
# method-specific TOML templates
# --------------------------------------------------

TANGENT_CONE = """\
# Generated by: flow-inviscid init tangent-cone

[method]
name = "tangent_cone"
"""

NEWTONIAN = """\
# Generated by: flow-inviscid init newtonian
# Edit the three sections below, then run: flow-inviscid solve

[method]
name = "newtonian"

[flow_conditions]
# Path to a flow-state JSON file (generate with: flow-state ... --output freestream.json)
file = "freestream.json"

[body]
# Two-column whitespace-separated file: x  y  (SI units, metres)
geometry_file = "body.dat"
# Coordinate system: "axisymmetric" (cone, ogive) or "2d" (wedge, airfoil)
geometry_type = "axisymmetric"

[output]
file   = "newtonian_result.dat"
format = "tecplot"
"""

SHOCK_EXPANSION = """\
# Generated by: flow-inviscid init shock-expansion

[method]
name = "shock_expansion"
"""

# --------------------------------------------------
# registry: method name -> template string
# --------------------------------------------------
TEMPLATES: dict[str, str] = {
    "tangent_cone":    TANGENT_CONE,
    "newtonian":       NEWTONIAN,
    "shock_expansion": SHOCK_EXPANSION,
}
