"""CLI handler for ``flow-inviscid solve``."""

# --------------------------------------------------
# load necessary modules
# --------------------------------------------------
from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

from flow_inviscid.config import read_config


# --------------------------------------------------
# solve command
# --------------------------------------------------
def cmd_solve(
    config: Annotated[
        Path,
        typer.Argument(help="Path to a TOML config file generated by `flow-inviscid init`."),
    ],
) -> None:
    """Run a solve from a config file.

    Reads the config file, validates it, dispatches to the method specified
    under [method] name, and writes output as configured.
    """

    # read and validate the config
    try:
        cfg = read_config(config)
    except (FileNotFoundError, ValueError) as exc:
        typer.echo(f"error: {exc}", err=True)
        raise typer.Exit(1)

    # dispatch placeholder (methods not yet implemented)
    typer.echo(f"Method: {cfg.method.name}")
    typer.echo("Not yet implemented.", err=True)
    raise typer.Exit(1)
